Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/04/2024
Var
// Seção de Declarações das variáveis 
   nota: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 400.4
   escreva("Resultado:", nota)

Fimalgoritmo